name: dartrqlite
description: A client of rqlite for dart
version: 1.0.0
homepage: https://github.com/summer-boythink/dartrqlite

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter_snowflake: ^0.0.4
  format: ^1.2.0
  http: ^0.13.5
  logger: ^1.2.2
  requests: ^4.7.0
  
